### ISSUE TITLE
GCTA version 1.21 (Oct 2013) vs 1.923beta (Aug 2019): is it safe to upgrade?

### ISSUE THREAD

**Issue by lcolladotor** [gusevlab/fusion_twas#15]
Hi,

I just realized today that there's a much newer version of GCTA (version 1.92.3beta; Aug 20, 2019) available from https://cnsgenomics.com/software/gcta/#Download than version 1.21 (Oct 16, 2013). Do you expect to run into any issues when using the latest version of GCTA compared to 1.21? I'm not familiar with GTCA and maybe you can identify if any of the changelog updates are relevant.

I found about this newer GCTA version because I was trying to find information on whether GCTA is multi-threaded or not, which I see at https://cnsgenomics.com/software/gcta/#Multi-threadcomputing that it is (and has been since version 1.1; though version 1.91.4beta added control through the `OMP_NUM_THREADS` environment variable). 

Best,
Leo

**Comment by sashagusev** [comment]
Hi Leo, thanks for pointing this out. The GCTA implementation that comes with FUSION has a re-implemented optimization function that we have found to be much more stable than standard GCTA when working with gene expression data from small samples. Since we are only using it to estimate heritability, I don't believe any of the more recent changes are relevant. If you're interested in the newer versions I would recommend running a few hundred genes to evaluate convergence first.
