### ISSUE TITLE
Getting weights for all genes

### ISSUE THREAD

**Issue by xsun1229** [gusevlab/fusion_twas#23]
Hi!
When I try to train weights for genes, some of them will be skipped. I understand there maybe some genes with low heritability and cannot pass the p-value threshold, but I'd like to get the results for all genes without skipping. How should I set the options? 
Thanks a lot!

**Comment by Bochao1** [comment]
Hi, 
I am wondering do you get both .hsq and .Rdat files as output? i only get .hsq in my case.
I am very new to this software. If you want share any experience, i am appreciated that you could contact me further (b.lin@umcutrecht.nl).

**Comment by sashagusev** [comment]
Hi, you can set the minimum heritability value for which to build models using the --hsq_p flag, if you set this to --hsq_p 1 then an attempt will be made to train models for all genes. In some cases a model will not converge and/or the heritability will be negative (a model violation) and so the gene will still be skipped.

**Comment by maegsul** [comment]
Hi, I'd like to ask a follow-up question on this.

I also trained my data using --hsq_p 1 option, so I modelled the prediction for every feature unless there is an issue due to the possible problems that @sashagusev mentioned above.

When I run TWAS on these training datasets + GWAS of interest, what I observed that it is more likely indeed to have significant (at TWAS P < 1E-5 levels, considering Bonf. correction) when the gene is heritable (with hsq_p < 0.05 that I specificed), However, for genes with hsq_p > 0.05, I have stilll considerable number of significant hits. The enrichment for hsq_p < 0.05 significant ones over hsq_p > 0.05 ones was about 2X only. 

Is this expected? I wanted to generate TWAS results for every gene across different custom panels I use to comment on the effect direction and other aspects better even when hsq_p > 0.05 (or, as FUSION uses this filter by default, let's say, hsq_p > 0.01) . However, I didn't expect that considerable number of features would still come out as TWAS significants even if the gene is "not heritable". I am unsure if I should report these, and if so, how. I am also not sure if it is wrong to look at results for "not heritable"  (high hsq_p values? if we can classify them like this) features in TWAS.

I am very curious what you think about this! I can also create a new issue if it is better, let me know.

PS: As a side note, for the generated results, the maximum hsq_p value I have is 0.5 (it is not 1 a I thought). Moreover, sometimes heritability estimate is quite high for a gene, but SE is also high -> placing it in the hsq_p > 0.05 category.
