### ISSUE TITLE
Uncertainty estimate?

### ISSUE THREAD

**Issue by carbocation** [gusevlab/fusion_twas#26]
Running `FUSION.assoc_test.R` yields a Z score and a P value, but aside from the directionality yielded by the Z score, I interpret these as effectively yielding the same information. Is it possible to obtain either a standard error or a beta in the output (either of which, with a Z score, would permit calculation of the other)?

**Comment by sashagusev** [comment]
Hi, sorry about the delay in responding. All of the FUSION analyses are done on the variance/Z-score scale so the Z-score is the primary statistic being inferred since there is no underlying "allele" that's being tested. However, you could convert the Z-score back into a standardized effect-size by assuming the standard error of the underlying association is approximately `\se = 1/sqrt(N)` where `N` is the GWAS sample size (assuming this is in the tens of thousands and so the approximation is fairly robust), and then back-calculating `\beta = Z * \se = Z/sqrt(N)`. This is an estimate of the `\beta` you would get from a regression of the phenotype on the centered and scaled predicted gene expression, if you were running the analysis with individual level data. Hope that helps!
