### ISSUE TITLE
All genes skipped when computing weights

### ISSUE THREAD

**Issue by kmfunder** [gusevlab/fusion_twas#29]
I have gene expression data from 11,535 microarray probes in 75 individuals and a covariates file containing demographic information, 3 principle components, and 10 PEER factors. I've been able to successfully run the compute_weights R script, but all of the genes ended up being skipped, so there was no output. Approximately 4500 were returned with 'GCTA could not converge' and the remaining genes did not pass the default heritability cutoff. Do you have any ideas on why this may have happened and how to proceed?

**Comment by kmfunder** [comment]
Another potentially relevant detail is that there were ~3,000 genes that returned negative heritability scores. Could this be an issue with sample size?

**Comment by sashagusev** [comment]
Yes, this looks like an issue with small sample size. We usually work with at least 100 samples for RNA-seq, and microarray may require more sample due to generally lower heritability. A few things you could try:
* Skipping the heritability check by setting a default value such as `--hsq_set 0.05` and then seeing if any of the models still produce significant cross-validation accuracy.
* Running a standard eQTL analysis first (e.g. using fastQTL) and then restricting to only those genes that have significant eQTLs, where you're confident there is at least a single associated SNP.
