### ISSUE TITLE
Error in post-process FUSION

### ISSUE THREAD

**Issue by SalimMegat** [gusevlab/fusion_twas#30]
Hi, 

For some of the work that I am doing I have been running conditional analysis for 1 of my significant TWAS locus. For some reason I get this warning for 1 of the 2 loci  : 

Warning : snp.cond.se = diag( sqrt( 1 - snp.ge.ld %*% ( cur.dinv ) %*% t(snp.ge.ld) ) ) : NaNs produced. 
I get a really high Chi-squared conditioned value like in the thousand range. I am not sure to completely understand what is wrong. Is it because the GWAS signal is so important that is driving most of the association ?  

Many thanks for your help and your patience ! 

Best, 

Salim.

**Comment by sashagusev** [comment]
Hi Salim, the conditional analysis is an approximation based on the summary data and it can sometimes lead to unstable solutions. This could be due to (a) an LD reference matrix that does not match the GWAS data well or has too few samples; (b) a complicated LD region. I would consider getting larger reference data for the LD reference, ideally a subset of the samples from the GWAS itself.

**Comment by SalimMegat** [comment]
Hi Sasha,

Thanks for taking the time to answer me ! I must admit that I let it go for
some time but it makes total sense !

Thanks

Salim.

**Comment by rodrigoduarte88** [comment]
Dear @sashagusev,

I’m encountering some warnings like “NaNs produced” during conditional analysis in my TWAS runs, and I wanted to better understand what they imply.

I generated my own FUSION weights using a dataset available to my lab (~500 European-ancestry samples). Although a suitable reference panel exists (e.g., 1000 Genomes European subset), I still get this warning for some chromosomes and GWASs.

To improve LD matching, I considered merging my cohort with 1000 Genomes to build a hybrid reference panel. However, I think that if people were to use my weights, then they would also need this tailored reference panel, which wouldn’t be available for sharing due to data access restrictions. For this reason, I think I should just stick to the analysis as is, so I just wanted to understand what the NaNs produced may imply.

My current understanding is that the "NaNs produced" warning reflects situations where complex LD or insufficient LD matching leads to unstable or undefined estimates during the conditional analysis — which could result in missed signals (i.e., false negatives). Would you say that interpretation is accurate?

Thanks in advance!

Best,
Rodrigo
