### ISSUE TITLE
Error in wgt.matrix[qc$flip, ] : incorrect number of dimensions (a solution)

### ISSUE THREAD

**Issue by hbliu** [gusevlab/fusion_twas#31]
A error was reported as following if there is no TRUE in qc$flip
Error in wgt.matrix[qc$flip, ] : incorrect number of dimensions

If you also meet this error message, try to modify the row 
wgt.matrix[qc$flip,] = -1 * wgt.matrix[qc$flip,]

 to

if(sum(qc$flip) > 0){
wgt.matrix[qc$flip,] = -1 * wgt.matrix[qc$flip,]
}

**Comment by sashagusev** [comment]
Hi, thanks for catching this. If qc$flip is empty or all FALSE the original code should still work without error. I think the error you are seeing reflects something more problematic in the data, either due to mismatching identifiers or duplicate identifiers. I would not recommend modifying the code in this way but localizing the problem to the inputs.

**Comment by Xinyu-Sun** [comment]
I noticed the similar issue recently. In `FUSION.post_process.R`:
https://github.com/gusevlab/fusion_twas/blob/e1ba5f7f3907e6f586f7fb5bb115b35cc0d3c0c2/FUSION.post_process.R#L166

In R, when you subset a matrix down to a single column, R automatically simplifies it to a vector unless you explicitly tell it not to. 

We probably need to specify `drop=FALSE` like how it is implemented in the other script: `wgt.matrix = wgt.matrix[m.keep,,drop=F]`
