### ISSUE TITLE
Best model specified as enet, yet all values in wgt.matrix are reported as 0

### ISSUE THREAD

**Issue by travismize** [gusevlab/fusion_twas#37]
Hello,

While parsing some of the weights obtained from http://gusevlab.org/projects/fusion/ (GTEx v7), I have noticed that the model with the highest R^2 is enet, yet the reported values in the wgt.matrix for enet are all 0. 

Example files are: Brain_Caudate_basal_ganglia.ENSG00000162368.9.wgt.RDat, Brain_Caudate_basal_ganglia.ENSG00000230092.3.wgt.RDat  

I am attempting to generate a list of SNPs from the best model of each weight, based on the model's specifications, but am unable to do so when all SNPs have a reported coefficient of 0.

[problematic_weights.zip](https://github.com/gusevlab/fusion_twas/files/6462470/problematic_weights.zip)

Thank you

**Comment by sashagusev** [comment]
Hi, thanks for the delay and good catch. I think this is due to some stochasticity in the weights training. The R2 is computed by cross-validation, then a final set of weights is trained on all the data. It's possible that in this final weights a model that had significant R2 performance converges to all zero weights. I think the most likely interpretation is that this is a weak or unstable model and shouldn't be used for prediction. In principle you can revert to the `top1` model instead if you need to test this gene.
