### ISSUE TITLE
perform TWAS using weights of GTEx(version 8)

### ISSUE THREAD

**Issue by biolyn** [gusevlab/fusion_twas#43]
Hi
I'm performing the TWAS analysis using weights of GTEx(version 8).
The following datasets are based on hg19:

1. The LD reference data (https://data.broadinstitute.org/alkesgroup/FUSION/LDREF.tar.bz2),
2. The glist-hg19 (https://github.com/gusevlab/fusion_twas/blob/master/glist-hg19),
3. My own GWAS summary data.

But the weights of GTEx(version 8) were based on the hg38. 
Therefore, to update the LD reference data, glist-hg19 ,and the GWAS data to hg38, I do the following steps:

1. Download the LD reference data (https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/GRCh38/plink_files.tgz) from https://alkesgroup.broadinstitute.org/LDSCORE/GRCh38/;
2. Download the glist-hg38 (https://www.cog-genomics.org/static/bin/plink/glist-hg38) from https://www.cog-genomics.org/plink/1.9/resources;
3. Using the liftover tool (http://hgdownload.cse.ucsc.edu/downloads.html) to update the GWAS data to hg38.

After finishing the steps, I perform the TWAS and further analysis (Joint/conditional tests, permutation test, and so on).
I'm wondering the above steps are correct or not?

Thanks!

**Comment by emiuga** [comment]
Hello,
I'm wondering about the same. Particularly when doing joint/conditional analysis.
1. To my understanding, it does not matter if your GWAS is on hg19, because the rsID# will be used to map to LD panel.
2. However, I'm not sure how does it work in the conditional analysis:
     2.1 Should I convert gene positions into hg19 coordinates, in order to be properly mapped onto the LD panel and GWAS sumstats?
     2.2 Or, would it be solved by using the LD panel (plink files) on built hg38?
3. Also, is there a difference of defining gene position as TSS/TES (in FUSION weights usually corresponding to 1 bp) or as the coding start/end position (i.e. full gene length)?

Thanks and best!

**Comment by Fei-Yang666** [comment]
Hi biolyn and emiuga,

Did you figure out this issue about different genome builds? I am a little bit  confused about the P0 and P1 gene position in pos file, should I used grch37 which is same as the provided 1000 genome LD reference ?  Or grch38 is also okay?  My feature weights were calculated based on grch38, and my gwas is grch37. 

Based on the author's answer in this question https://github.com/gusevlab/fusion_twas/issues/32, it doesn't matter that weights was calculated with different genome builds as it is all rsID indexed.  But how about the plotting step and  conditional step? 

Looking forward to hearing your thoughts

Many thanks

Fei

**Comment by emiuga** [comment]
Hello @Fei-Yang666 

As you mention, rsIDs are used in the TWAS association tests and the genome built does not matter.
However, I think is better to harmonize genome coordinates when running joint/conditional analysis. This because positions are needed for plotting genes: both TWAS significant genes, as well as "background genes" which added to the plot in gray color. 

In the GWAS conditional analysis (run on TWAS significant genes from each chromosome at a time), I believe is done by using overlapping rsIDs between LDref panel, sumstats, and weights, to obtain the subset of cis-SNPs with corresponding genotypes from the LD ref panel, GWAS Z-scores, weights from the prediction models, and the associated TWAS Z-scores from the input genes.

Only when plotting genes into non-overlapping loci, I think LDref panel and gene coordinates (from TWAS output, *pos weight input file) should be in the same genome built (so to map back genes to loci correctly), if I'm understanding the code correctly.

These are my thoughts/ current workaround:
1. To stick to grch37 built, I formatted the TWAS output files (*.dat) by replacing P0/P1 for the grch37 genome coordinates.
         - To match ENSEMBL ids with gene_symbols I downloaded GTEx file: GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct.
         -  To get grch37 gene coordinates, I downloaded GTEx gene file from http://genome.ucsc.edu/cgi-bin/hgTables (select Expression/ GTEx Gene V8; check columns on "describe table schema"). Then I merged to FUSION output and replaced ID for name, and P0/P1 for chromStart/chromEnd values).
         - I then run conditional analysis using these formatted output. 
         - Alternatively, you could format the *pos file before running TWAS analysis. 
         - Also, you could harmonize gene coordinates to the "glist-hg19" PLINK file in the FUSION folder, which is used to plot "background genes", but I'm not sure how good overlap it has with the genes from the prediction models.

2. If you wanna use grch38 instead, I think you should use LDref files in grch38 genome built, to map genes to loci correctly. In addition, you would need to replace the "glist-hg19"  file in FUSION folder, for a "glist-hg38" which you can download from PLINK <<https://www.cog-genomics.org/plink/1.9/resources#genelist>> . Then you will need to modify post-script by replacing the name, as hg19 is built in.  
    

Hope this helps.
Best,
Emilio

**Comment by sashagusev** [comment]
Hi all, thanks for the discussion, just chiming in to agree with Emilio. The _statistical_ aspects of FUSION only rely on SNP identifiers between GWAS, weights, and the LDREF and do not depend on the SNP positions at all; so the same TWAS Z-score and P-value will come out regardless of genome build. However, for visualization (and anything that requires physical windows) the physical ordering of SNPs will matter, as well as what SNPs are considered within a physical window.
