### ISSUE TITLE
Perform TWAS with GWAS data from non-European ancestry

### ISSUE THREAD

**Issue by baike687** [gusevlab/fusion_twas#45]
Hi,

Recently, we plan to perform a TWAS using a GWAS summary statistics (about cancer research) from a population of non-European ancestry (e.g., Asian population), I was wondering whether I can use a LD reference data from Asian population, and is it appropriate to conduct a TWAS using non-European population GWAS data?

Thank you, hope you have a nice day!

Baike

**Comment by sashagusev** [comment]
Hi Baike, thanks for the question. In order to be statistically valid the TWAS analysis should use LD from the target/GWAS population. So in your case it sounds like you would need an Asian ancestry LD reference panel. It is still okay to use weights trained in Europeans but does not guarentee that the prediction accuracy will translate, and so you may lose some power when porting across populations.

Best,
Sasha
